name: Build LaTeX Documents

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          set-safe-directory: true

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /__w/DAI-Assignments/DAI-Assignments

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            A*/**/**.tex
          dir_names: true
          dir_names_max_depth: "1"

      - name: List all changed files
        run: echo "CHANGED_DIRS=${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq

      - name: Download previous release assets
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: |
          response=$(curl -L -w "%{http_code}" -o response.json -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.CUSTOM_GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          mkdir -p build
          if [ "$response" -eq 200 ]; then
            jq -r '.assets[] | "\(.id) \(.name)"' response.json | while read -r id name; do curl -L -H "Accept: application/octet-stream" -H "Authorization: Bearer ${{ secrets.CUSTOM_GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${{ github.repository }}/releases/assets/$id" --output "build/$name"; done
          else
            echo "No previous release found or error retrieving release. HTTP Status: $response"
          fi

      - name: Build LaTeX documents
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: |
          mkdir -p build
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            cd "$dir"
            latexmk -pdf -file-line-error -interaction=nonstopmode
            rm -f "../build/${dir}.pdf"
            mv main.pdf "../build/${dir}.pdf"
            cd ..
          done

      - name: Set Release Time
        run: |
          echo "RELEASE_TIME=$(date +%Y%m%d-%H%M%S)" >> ${GITHUB_ENV}

      - name: Create new release with all PDFs
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.pdf
          name: "DAI-${{ env.RELEASE_TIME }}"
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tag_name: "dai-assignments-${{ env.RELEASE_TIME }}"
          draft: false
          prerelease: false
          make_latest: "true"
