name: Build LaTeX Documents

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Build LaTeX documents
        run: |
          for dir in ass*/; do
            cd "$dir"
            latexmk -pdf -file-line-error -interaction=nonstopmode
            mv main.pdf "../${dir%/}.pdf"
            cd ..
          done

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: ./*.pdf
